module.exports = {
  structure: {
    webAppRoot: 'app',
    targetWebRoot: 'apps/web',
    targetAdminRoot: 'apps/admin',
    backendLegacyRoot: 'backend/src/modules',
    backendTargetRoot: 'backend/modules',
    commonRoot: 'backend/common',
    configRoot: 'backend/config',
    infrastructureRoot: 'backend/infrastructure',
    sharedRoot: 'shared',
  },
  fileMigrationMap: [
    ['app/admin', 'apps/admin'],
    ['app/login', 'apps/web/auth/login'],
    ['app/signup', 'apps/web/auth/signup'],
    ['app/verify', 'apps/web/auth/verify'],
    ['app/dashboard', 'apps/web/dashboard'],
    ['app/courses', 'apps/web/courses'],
    ['app/learn', 'apps/web/learn'],
    ['app/events', 'apps/web/events'],
    ['app/mentors', 'apps/web/mentors'],
    ['app/investors', 'apps/web/investors'],
    ['app/api', 'backend/modules/*/*.routes.js'],
    ['lib/auth.js', 'backend/modules/auth/auth.service.js'],
    ['lib/sessionManager.js', 'backend/modules/auth/auth.middleware.js'],
    ['lib/courseService.js', 'backend/modules/courses/courses.service.js'],
    ['lib/mvpCourseService.js', 'backend/modules/courses/courses.service.js'],
    ['lib/courseProgressService.js', 'backend/modules/enrollments/enrollments.service.js'],
    ['lib/assessmentService.js', 'backend/modules/analytics/analytics.service.js'],
    ['lib/activityLogger.js', 'backend/modules/analytics/analytics.service.js'],
    ['lib/dashboardService.js', 'backend/modules/analytics/analytics.service.js'],
    ['lib/apiClient.js', 'backend/common/index.js'],
    ['lib/security.js', 'backend/common/index.js'],
    ['lib/rateLimiter.js', 'backend/common/index.js'],
    ['lib/sanitizer.js', 'backend/common/index.js'],
    ['backend/src/modules/auth', 'backend/modules/auth'],
    ['backend/src/modules/users', 'backend/modules/users'],
    ['backend/src/modules/courses', 'backend/modules/courses'],
    ['backend/src/modules/enrollments', 'backend/modules/enrollments'],
    ['backend/src/modules/payments', 'backend/modules/payments'],
    ['backend/src/modules/certificates', 'backend/modules/certificates'],
    ['backend/src/modules/profiles', 'backend/modules/mentors'],
    ['backend/src/modules/data', 'backend/modules/analytics'],
    ['backend/src/config/env.js', 'backend/config/index.js'],
    ['backend/src/config/db.js', 'backend/infrastructure/index.js'],
    ['backend/src/utils/*', 'backend/common/index.js'],
  ],
  duplicateCandidates: [
    'components/HeroSectionNew.js',
    'components/HeroSectionClean.js',
    'components/EcosystemHeroNew.js',
    'components/EcosystemHeroSection.js',
    'components/EcosystemHeroSectionV2.js',
    'components/ErrorBoundary.js',
    'components/ClientErrorBoundary.js',
    'backend/src/modules/courses/course.model.js',
    'backend/src/modules/courses/course2.model.js',
    'lib/courseService.js',
    'lib/mvpCourseService.js',
  ],
  supabaseInventory: [
    'lib/supabaseClient.js',
    'lib/supabaseOptimized.js',
    'database/mvp-schema.sql',
    'supabase-admin-schema.sql',
    'supabase-investors-schema.sql',
    'supabase-mentors-schema.sql',
    'supabase-schema.sql',
    'supabase/',
  ],
};
